DELETE FROM programs WHERE program_code = 'CSE' OR program_code = 'BBA' OR program_code LIKE 'BBA\_%';

INSERT INTO programs (program_code, course_code, course_name, credits, category) VALUES
('CSE', 'ENG102', 'Introduction to Composition', 3, 'waivable'),
('CSE', 'MAT112', 'College Algebra', 0, 'waivable'),
('CSE', 'ENG103', 'Intermediate Composition', 3, 'GED_required'),
('CSE', 'ENG105', 'Advanced Writing Skills', 3, 'GED_required'),
('CSE', 'ENG111', 'Public Speaking', 3, 'GED_required'),
('CSE', 'PHI101', 'Introduction to Philosophy', 3, 'GED_required'),
('CSE', 'PHI104', 'Introduction to Ethics', 3, 'GED_required'),
('CSE', 'HIS101', 'Bangladesh History & Culture', 3, 'GED_required'),
('CSE', 'HIS102', 'World Civilization', 3, 'GED_required'),
('CSE', 'ECO101', 'Intro to Microeconomics', 3, 'GED_choice_1'),
('CSE', 'ECO104', 'Intro to Macroeconomics', 3, 'GED_choice_1'),
('CSE', 'POL101', 'Intro to Political Science', 3, 'GED_choice_2'),
('CSE', 'POL104', 'Political Science', 3, 'GED_choice_2'),
('CSE', 'SOC101', 'Intro to Sociology', 3, 'GED_choice_3'),
('CSE', 'ANT101', 'Anthropology', 3, 'GED_choice_3'),
('CSE', 'ENV203', 'Environmental Studies', 3, 'GED_choice_3'),
('CSE', 'GEO205', 'Geography', 3, 'GED_choice_3'),
('CSE', 'CSE101', 'Intro to Python Programming', 3, 'catalog_only'),
('CSE', 'CSE145', 'Intro to AI', 3, 'catalog_only'),
('CSE', 'CSE226', 'Fundamentals of Vibe Coding', 3, 'catalog_only'),
('CSE', 'CSE115', 'Programming Language I', 3, 'SEPS_core'),
('CSE', 'CSE115L', 'Programming Language I Lab', 1, 'SEPS_core'),
('CSE', 'MAT116', 'Pre-Calculus', 3, 'SEPS_core'),
('CSE', 'MAT120', 'Calculus I', 3, 'SEPS_core'),
('CSE', 'MAT125', 'Linear Algebra', 3, 'SEPS_core'),
('CSE', 'MAT130', 'Calculus II', 3, 'SEPS_core'),
('CSE', 'MAT250', 'Calculus III', 3, 'SEPS_core'),
('CSE', 'MAT350', 'Complex Variables', 3, 'SEPS_core'),
('CSE', 'MAT361', 'Discrete Mathematics II', 3, 'SEPS_core'),
('CSE', 'PHY107', 'Physics I', 3, 'SEPS_core'),
('CSE', 'PHY107L', 'Physics I Lab', 1, 'SEPS_core'),
('CSE', 'PHY108', 'Physics II', 3, 'SEPS_core'),
('CSE', 'PHY108L', 'Physics II Lab', 1, 'SEPS_core'),
('CSE', 'CHE101', 'Chemistry I', 3, 'SEPS_core'),
('CSE', 'CHE101L', 'Chemistry I Lab', 1, 'SEPS_core'),
('CSE', 'BIO103', 'Biology I', 3, 'SEPS_core'),
('CSE', 'BIO103L', 'Biology I Lab', 1, 'SEPS_core'),
('CSE', 'CEE110', 'Engineering Drawing', 1, 'SEPS_core'),
('CSE', 'CSE173', 'Discrete Mathematics', 3, 'major_core'),
('CSE', 'CSE215', 'Programming Language II', 3, 'major_core'),
('CSE', 'CSE215L', 'Programming Language II Lab', 1, 'major_core'),
('CSE', 'CSE225', 'Data Structures & Algorithms', 3, 'major_core'),
('CSE', 'CSE225L', 'Data Structures & Algorithms Lab', 1, 'major_core'),
('CSE', 'CSE231', 'Digital Logic Design', 3, 'major_core'),
('CSE', 'CSE231L', 'Digital Logic Design Lab', 1, 'major_core'),
('CSE', 'CSE299', 'Junior Design Project', 1, 'major_core'),
('CSE', 'CSE311', 'Database Management Systems', 3, 'major_core'),
('CSE', 'CSE311L', 'Database Management Systems Lab', 1, 'major_core'),
('CSE', 'CSE323', 'Operating Systems Design', 3, 'major_core'),
('CSE', 'CSE325', 'Operating Systems', 3, 'major_core'),
('CSE', 'CSE327', 'Software Engineering', 3, 'major_core'),
('CSE', 'CSE331', 'Microprocessor Interfacing & Embedded', 3, 'major_core'),
('CSE', 'CSE331L', 'Microprocessor Interfacing Lab', 1, 'major_core'),
('CSE', 'CSE332', 'Computer Organization & Architecture', 3, 'major_core'),
('CSE', 'CSE373', 'Design & Analysis of Algorithms', 3, 'major_core'),
('CSE', 'CSE425', 'Concepts of Programming Languages', 3, 'major_core'),
('CSE', 'EEE141', 'Electrical Circuits I', 3, 'major_core'),
('CSE', 'EEE141L', 'Electrical Circuits I Lab', 1, 'major_core'),
('CSE', 'EEE111', 'Analog Electronics I', 3, 'major_core'),
('CSE', 'EEE111L', 'Analog Electronics I Lab', 1, 'major_core'),
('CSE', 'CSE499A', 'Senior Capstone Design I', 2, 'capstone'),
('CSE', 'CSE499B', 'Senior Capstone Design II', 2, 'capstone'),
('CSE', 'EEE452', 'Engineering Economics', 3, 'capstone'),
('CSE', 'OPEN_ELECTIVE', 'Open Elective', 3, 'GED_open_elective'),
('CSE', 'CSE421', 'Machine Learning', 3, 'elective_400'),
('CSE', 'CSE422', 'Simulation and Modeling', 3, 'elective_400'),
('CSE', 'CSE423', 'Advanced Operating Systems', 3, 'elective_400'),
('CSE', 'CSE424', 'Object-Oriented Software Dev', 3, 'elective_400'),
('CSE', 'CSE427', 'Software Quality Assurance', 3, 'elective_400'),
('CSE', 'CSE428', 'Software Project Management', 3, 'elective_400'),
('CSE', 'CSE429', 'Software System Architecture', 3, 'elective_400'),
('CSE', 'CSE433', 'Advanced Computer Architecture', 3, 'elective_400'),
('CSE', 'CSE438', 'Networks & Distributed Systems', 3, 'elective_400'),
('CSE', 'CSE439', 'Advanced Computer Networks', 3, 'elective_400'),
('CSE', 'CSE440', 'Artificial Intelligence (Adv)', 3, 'elective_400'),
('CSE', 'CSE445', 'Machine Learning (Adv)', 3, 'elective_400'),
('CSE', 'CSE448', 'Neural Networks', 3, 'elective_400'),
('CSE', 'CSE465', 'Pattern Recognition', 3, 'elective_400'),
('CSE', 'CSE467', 'Image Processing', 3, 'elective_400'),
('CSE', 'CSE472', 'Advanced Algorithms', 3, 'elective_400'),
('CSE', 'CSE473', 'Parallel Processing', 3, 'elective_400'),
('CSE', 'CSE474', 'Computational Complexity', 3, 'elective_400'),
('CSE', 'CSE475', 'Automata Theory & Formal Language', 3, 'elective_400'),
('CSE', 'CSE478', 'Graph Theory', 3, 'elective_400'),
('BBA', 'ECO101', 'Intro to Microeconomics', 3, 'school_core'),
('BBA', 'ECO104', 'Intro to Macroeconomics', 3, 'school_core'),
('BBA', 'MIS107', 'Introduction to Computers', 3, 'school_core'),
('BBA', 'BUS251', 'Business Communication', 3, 'school_core'),
('BBA', 'BUS172', 'Introduction to Statistics', 3, 'school_core'),
('BBA', 'BUS173', 'Applied Statistics', 3, 'school_core'),
('BBA', 'BUS135', 'Business Mathematics', 3, 'school_core'),
('BBA', 'ACT201', 'Intro to Financial Accounting', 3, 'major_core'),
('BBA', 'ACT202', 'Intro to Managerial Accounting', 3, 'major_core'),
('BBA', 'FIN254', 'Intro to Financial Management', 3, 'major_core'),
('BBA', 'LAW200', 'Legal Environment of Business', 3, 'major_core'),
('BBA', 'INB372', 'International Business', 3, 'major_core'),
('BBA', 'MKT202', 'Introduction to Marketing', 3, 'major_core'),
('BBA', 'BUS101', 'Introduction to Business', 3, 'major_core'),
('BBA', 'MIS207', 'Management Information Systems', 3, 'major_core'),
('BBA', 'MGT212', 'Principles of Management', 3, 'major_core'),
('BBA', 'MGT351', 'Human Resource Management', 3, 'major_core'),
('BBA', 'MGT314', 'Production Management', 3, 'major_core'),
('BBA', 'MGT368', 'Entrepreneurship', 3, 'major_core'),
('BBA', 'MGT489', 'Strategic Management', 3, 'major_core'),
('BBA', 'ENG103', 'Intermediate Composition', 3, 'GED_required'),
('BBA', 'ENG105', 'Advanced Composition', 3, 'GED_required'),
('BBA', 'PHI401', 'Ethics / Philosophy', 3, 'GED_required'),
('BBA', 'BUS401', 'Business Ethics', 3, 'GED_required'),
('BBA', 'INT101', 'Introduction to International Relations', 3, 'GED_required'),
('BBA', 'ECO249', 'Socio Economic Profiles of Bangladesh', 3, 'GED_required'),
('BBA', 'BEN205', 'Bengali Literature', 3, 'GED_choice_lang'),
('BBA', 'ENG115', 'Advanced English', 3, 'GED_choice_lang'),
('BBA', 'CHN101', 'Chinese Language', 3, 'GED_choice_lang'),
('BBA', 'HIS101', 'Bangladesh History & Culture', 3, 'GED_choice_his'),
('BBA', 'HIS102', 'World Civilization', 3, 'GED_choice_his'),
('BBA', 'HIS103', 'History of South Asia', 3, 'GED_choice_his'),
('BBA', 'HIS205', 'History of Science', 3, 'GED_choice_his'),
('BBA', 'POL101', 'Intro to Political Science', 3, 'GED_choice_pol'),
('BBA', 'POL104', 'Political Science', 3, 'GED_choice_pol'),
('BBA', 'PAD201', 'Public Administration', 3, 'GED_choice_pol'),
('BBA', 'SOC101', 'Intro to Sociology', 3, 'GED_choice_soc'),
('BBA', 'GEO205', 'Geography', 3, 'GED_choice_soc'),
('BBA', 'ANT101', 'Anthropology', 3, 'GED_choice_soc'),
('BBA', 'BIO103', 'Biology I', 3, 'GED_choice_sci'),
('BBA', 'ENV107', 'Environmental Science', 3, 'GED_choice_sci'),
('BBA', 'PBH101', 'Public Health', 3, 'GED_choice_sci'),
('BBA', 'PSY101', 'Intro to Psychology', 3, 'GED_choice_sci'),
('BBA', 'PHY107', 'Physics I', 3, 'GED_choice_sci'),
('BBA', 'CHE101', 'Chemistry I', 3, 'GED_choice_sci'),
('BBA', 'BIO103L', 'Biology I Lab', 1, 'GED_choice_lab'),
('BBA', 'ENV107L', 'Environmental Science Lab', 1, 'GED_choice_lab'),
('BBA', 'PBH101L', 'Public Health Lab', 1, 'GED_choice_lab'),
('BBA', 'PSY101L', 'Intro to Psychology Lab', 1, 'GED_choice_lab'),
('BBA', 'PHY107L', 'Physics I Lab', 1, 'GED_choice_lab'),
('BBA', 'CHE101L', 'Chemistry I Lab', 1, 'GED_choice_lab'),
('BBA', 'ENG102', 'Introduction to Composition', 3, 'waivable'),
('BBA', 'BUS112', 'Intro to Business Mathematics', 3, 'waivable'),
('BBA', 'BUS498', 'Internship', 4, 'internship'),
('BBA', 'FREE_ELEC_1', 'Free Elective 1', 3, 'free_elective'),
('BBA', 'FREE_ELEC_2', 'Free Elective 2', 3, 'free_elective'),
('BBA', 'FREE_ELEC_3', 'Free Elective 3', 3, 'free_elective'),
('BBA_ACT', 'ACT310', 'Intermediate Accounting I', 3, 'concentration_core'),
('BBA_ACT', 'ACT320', 'Intermediate Accounting II', 3, 'concentration_core'),
('BBA_ACT', 'ACT360', 'Advanced Managerial Accounting', 3, 'concentration_core'),
('BBA_ACT', 'ACT370', 'Taxation', 3, 'concentration_core'),
('BBA_ACT', 'ACT380', 'Accounting Info Systems', 3, 'concentration_elective'),
('BBA_ACT', 'ACT460', 'International Accounting', 3, 'concentration_elective'),
('BBA_ACT', 'ACT430', 'Forensic Accounting', 3, 'concentration_elective'),
('BBA_ACT', 'ACT410', 'Advanced Accounting', 3, 'concentration_elective'),
('BBA_FIN', 'FIN433', 'Investment Analysis', 3, 'concentration_core'),
('BBA_FIN', 'FIN440', 'International Finance', 3, 'concentration_core'),
('BBA_FIN', 'FIN435', 'Financial Institutions', 3, 'concentration_core'),
('BBA_FIN', 'FIN444', 'Financial Markets', 3, 'concentration_core'),
('BBA_FIN', 'FIN455', 'Derivatives', 3, 'concentration_elective'),
('BBA_FIN', 'FIN464', 'Corporate Finance', 3, 'concentration_elective'),
('BBA_FIN', 'FIN470', 'Insurance and Risk Management', 3, 'concentration_elective'),
('BBA_FIN', 'FIN480', 'Behavioural Finance', 3, 'concentration_elective'),
('BBA_FIN', 'FIN410', 'Financial Statement Analysis', 3, 'concentration_elective'),
('BBA_MKT', 'MKT337', 'Promotional Management', 3, 'concentration_core'),
('BBA_MKT', 'MKT344', 'Consumer Behaviour', 3, 'concentration_core'),
('BBA_MKT', 'MKT460', 'Strategic Marketing', 3, 'concentration_core'),
('BBA_MKT', 'MKT470', 'Marketing Research', 3, 'concentration_core'),
('BBA_MKT', 'MKT412', 'Services Marketing', 3, 'concentration_elective'),
('BBA_MKT', 'MKT465', 'Brand Management', 3, 'concentration_elective'),
('BBA_MKT', 'MKT382', 'International Marketing', 3, 'concentration_elective'),
('BBA_MKT', 'MKT417', 'Export-Import Management', 3, 'concentration_elective'),
('BBA_MKT', 'MKT330', 'Digital Marketing', 3, 'concentration_elective'),
('BBA_MKT', 'MKT450', 'Marketing Channels', 3, 'concentration_elective'),
('BBA_MKT', 'MKT355', 'Retail Management', 3, 'concentration_elective'),
('BBA_MKT', 'MKT445', 'Sales Management', 3, 'concentration_elective'),
('BBA_MKT', 'MKT475', 'Marketing Analytics', 3, 'concentration_elective'),
('BBA_MGT', 'MGT321', 'Organizational Behavior', 3, 'concentration_core'),
('BBA_MGT', 'MGT330', 'Designing Effective Orgs', 3, 'concentration_core'),
('BBA_MGT', 'HRM370', 'Managerial Skill Development', 3, 'concentration_core'),
('BBA_MGT', 'MGT410', 'Org Development & Change', 3, 'concentration_core'),
('BBA_MGT', 'MGT350', 'Managing Quality', 3, 'concentration_elective'),
('BBA_MGT', 'MGT490', 'Project Management', 3, 'concentration_elective'),
('BBA_MGT', 'HRM470', 'Negotiations', 3, 'concentration_elective'),
('BBA_MGT', 'HRM450', 'Industrial Relations', 3, 'concentration_elective'),
('BBA_MGT', 'MIS320', 'IT for Managers', 3, 'concentration_elective'),
('BBA_HRM', 'HRM340', 'Training and Development', 3, 'concentration_core'),
('BBA_HRM', 'HRM360', 'Planning and Staffing', 3, 'concentration_core'),
('BBA_HRM', 'HRM380', 'Compensation Theory and Practice', 3, 'concentration_core'),
('BBA_HRM', 'HRM450', 'Industrial Relations', 3, 'concentration_core'),
('BBA_HRM', 'HRM370', 'Managerial Skill Development', 3, 'concentration_elective'),
('BBA_HRM', 'HRM499', 'HRM Capstone', 3, 'concentration_elective'),
('BBA_HRM', 'HRM470', 'Negotiations', 3, 'concentration_elective'),
('BBA_MIS', 'MIS210', 'Concepts of Computer Programming', 3, 'concentration_core'),
('BBA_MIS', 'MIS310', 'Systems Analysis & Design', 3, 'concentration_core'),
('BBA_MIS', 'MIS320', 'IT for Managers', 3, 'concentration_core'),
('BBA_MIS', 'MIS470', 'Management of IT', 3, 'concentration_core'),
('BBA_MIS', 'MIS330', 'Digital Marketing & Social Networks', 3, 'concentration_elective'),
('BBA_MIS', 'MIS410', 'Business Intelligence', 3, 'concentration_elective'),
('BBA_MIS', 'MIS450', 'ERP Systems', 3, 'concentration_elective'),
('BBA_MIS', 'MGT490', 'Project Management', 3, 'concentration_elective'),
('BBA_MIS', 'MIS499', 'MIS Capstone', 3, 'concentration_elective'),
('BBA_SCM', 'SCM310', 'Supply Chain Fundamentals', 3, 'concentration_core'),
('BBA_SCM', 'SCM320', 'Supply Chain Planning', 3, 'concentration_core'),
('BBA_SCM', 'SCM450', 'Advanced Supply Chain', 3, 'concentration_core'),
('BBA_SCM', 'MGT460', 'Operations Management', 3, 'concentration_core'),
('BBA_SCM', 'MGT360', 'Global Supply Chain', 3, 'concentration_elective'),
('BBA_SCM', 'MGT390', 'Warehouse Management', 3, 'concentration_elective'),
('BBA_SCM', 'MGT470', 'Quality Management', 3, 'concentration_elective'),
('BBA_SCM', 'MGT490', 'Project Management', 3, 'concentration_elective'),
('BBA_ECO', 'ECO201', 'Intermediate Microeconomics', 3, 'concentration_core'),
('BBA_ECO', 'ECO204', 'Intermediate Macroeconomics', 3, 'concentration_core'),
('BBA_ECO', 'ECO348', 'Mathematical Economics', 3, 'concentration_core'),
('BBA_ECO', 'ECO328', 'Econometrics', 3, 'concentration_core'),
('BBA_ECO', 'ECO244', 'Applied Economics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO301', 'Microeconomic Theory', 3, 'concentration_elective'),
('BBA_ECO', 'ECO304', 'Macroeconomic Theory', 3, 'concentration_elective'),
('BBA_ECO', 'ECO317', 'Money & Banking', 3, 'concentration_elective'),
('BBA_ECO', 'ECO329', 'Applied Econometrics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO343', 'Public Finance', 3, 'concentration_elective'),
('BBA_ECO', 'ECO354', 'Development Economics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO360', 'International Trade', 3, 'concentration_elective'),
('BBA_ECO', 'ECO372', 'Bangladesh Economy', 3, 'concentration_elective'),
('BBA_ECO', 'ECO380', 'Health Economics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO406', 'Economic Policy', 3, 'concentration_elective'),
('BBA_ECO', 'ECO410', 'Game Theory', 3, 'concentration_elective'),
('BBA_ECO', 'ECO414', 'Urban Economics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO415', 'Time Series', 3, 'concentration_elective'),
('BBA_ECO', 'ECO417', 'Financial Economics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO430', 'Managerial Economics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO436', 'Environmental Economics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO441', 'Labor Economics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO443', 'Industrial Organization', 3, 'concentration_elective'),
('BBA_ECO', 'ECO450', 'Research Methods', 3, 'concentration_elective'),
('BBA_ECO', 'ECO451', 'Monetary Economics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO460', 'International Finance', 3, 'concentration_elective'),
('BBA_ECO', 'ECO465', 'Political Economy', 3, 'concentration_elective'),
('BBA_ECO', 'ECO472', 'Economic History', 3, 'concentration_elective'),
('BBA_ECO', 'ECO474', 'Economic Growth', 3, 'concentration_elective'),
('BBA_ECO', 'ECO475', 'Panel Data', 3, 'concentration_elective'),
('BBA_ECO', 'ECO484', 'Experimental Economics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO485', 'Behavioural Economics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO486', 'Neuroeconomics', 3, 'concentration_elective'),
('BBA_ECO', 'ECO492', 'Special Topics', 3, 'concentration_elective'),
('BBA_INB', 'INB400', 'International Business Strategy', 3, 'concentration_core'),
('BBA_INB', 'INB490', 'INB Capstone', 3, 'concentration_core'),
('BBA_INB', 'INB480', 'Global Operations', 3, 'concentration_core'),
('BBA_INB', 'MKT382', 'International Marketing', 3, 'concentration_core'),
('BBA_INB', 'INB410', 'Cross-Cultural Management', 3, 'concentration_elective'),
('BBA_INB', 'INB350', 'Global Marketing', 3, 'concentration_elective'),
('BBA_INB', 'INB355', 'Global Finance', 3, 'concentration_elective'),
('BBA_INB', 'INB415', 'International Negotiations', 3, 'concentration_elective'),
('BBA_INB', 'INB450', 'Global Entrepreneurship', 3, 'concentration_elective'),
('BBA_INB', 'INB495', 'Special Topics in INB', 3, 'concentration_elective'),
('BBA_INB', 'MKT417', 'Export-Import Management', 3, 'concentration_elective');
